package edu.ldcollege.orm.domain;

import java.util.Date;

public class LdCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcourse.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcourse.courseTitle
     *
     * @mbg.generated
     */
    private String coursetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcourse.days
     *
     * @mbg.generated
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ldcourse.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcourse.id
     *
     * @return the value of ldcourse.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcourse.id
     *
     * @param id the value for ldcourse.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcourse.courseTitle
     *
     * @return the value of ldcourse.courseTitle
     *
     * @mbg.generated
     */
    public String getCoursetitle() {
        return coursetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcourse.courseTitle
     *
     * @param coursetitle the value for ldcourse.courseTitle
     *
     * @mbg.generated
     */
    public void setCoursetitle(String coursetitle) {
        this.coursetitle = coursetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcourse.days
     *
     * @return the value of ldcourse.days
     *
     * @mbg.generated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcourse.days
     *
     * @param days the value for ldcourse.days
     *
     * @mbg.generated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ldcourse.createTime
     *
     * @return the value of ldcourse.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ldcourse.createTime
     *
     * @param createtime the value for ldcourse.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}