package edu.ldcollege.orm.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import edu.ldcollege.orm.domain.LdCourse;

public interface LdCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcourse
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ldcourse",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcourse
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ldcourse (id, courseTitle, ",
        "days, createTime)",
        "values (#{id,jdbcType=INTEGER}, #{coursetitle,jdbcType=VARCHAR}, ",
        "#{days,jdbcType=INTEGER}, #{createtime,jdbcType=TIMESTAMP})"
    })
    int insert(LdCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcourse
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, courseTitle, days, createTime",
        "from ldcourse",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="courseTitle", property="coursetitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="days", property="days", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP)
    })
    LdCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcourse
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, courseTitle, days, createTime",
        "from ldcourse"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="courseTitle", property="coursetitle", jdbcType=JdbcType.VARCHAR),
        @Result(column="days", property="days", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<LdCourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ldcourse
     *
     * @mbg.generated
     */
    @Update({
        "update ldcourse",
        "set courseTitle = #{coursetitle,jdbcType=VARCHAR},",
          "days = #{days,jdbcType=INTEGER},",
          "createTime = #{createtime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LdCourse record);
}